apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-inception
spec:
  template:
    metadata:
      name: seed-inception
    spec:
      activeDeadlineSeconds: 7200
      containers:
      - name: seed
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "wget -O /seed/inception-v3-2016-03-01.tar.gz http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz && cd /seed/ && tar -xzf inception-v3-2016-03-01.tar.gz && rm inception-v3-2016-03-01.tar.gz"]
        volumeMounts:
        - name: seed
          mountPath: /seed
      restartPolicy: Never
      volumes:
      - name: seed
        persistentVolumeClaim:
          claimName: seed
