apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow-serving
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tensorflow-serving
    spec:
      containers:
      - name: serving
        image: bitnami/tensorflow-serving:latest
        securityContext:
          privileged: true
        ports:
          - containerPort: 8500
            protocol: TCP
        volumeMounts:
        - name: model
          mountPath: "/bitnami/model-data"
        - name: seed
          mountPath: "/mnt"
      initContainers:
      - name: load-model
        image: bitnami/tensorflow-inception:latest
        command: ["/opt/bitnami/tensorflow-inception/bazel-bin/tensorflow_serving/example/inception_saved_model","--checkpoint_dir=/mnt/inception-v3","--output_dir=/bitnami/model-data"]
        volumeMounts:
        - name: model
          mountPath: "/bitnami/model-data"
        - name: seed
          mountPath: "/mnt"
      volumes:
      - name: seed
        persistentVolumeClaim:
          claimName: seed
      - name: model
        emptyDir: {}
